CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS provider_lists (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  source_url text,
  server_url text,
  username text,
  provider_password text,
  expires_at timestamptz,
  provider_status text,
  status text NOT NULL DEFAULT 'unknown',
  max_connections integer NOT NULL DEFAULT 1,
  active_connections integer NOT NULL DEFAULT 0,
  last_sync_at timestamptz,
  last_error text,
  created_by text,
  provider_secret_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS clients (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text,
  phone text,
  plan text NOT NULL DEFAULT 'Mensal',
  list_id uuid REFERENCES provider_lists(id) ON DELETE SET NULL,
  device_limit integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'active',
  activation_code text UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS devices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id uuid REFERENCES clients(id) ON DELETE CASCADE,
  device_uid text,
  device_name text,
  platform text,
  last_seen_at timestamptz,
  status text NOT NULL DEFAULT 'offline',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS activations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id uuid REFERENCES clients(id) ON DELETE CASCADE,
  device_id uuid REFERENCES devices(id) ON DELETE SET NULL,
  activation_code text,
  activated_at timestamptz,
  revoked_at timestamptz
);

CREATE TABLE IF NOT EXISTS sync_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  list_id uuid REFERENCES provider_lists(id) ON DELETE CASCADE,
  status text,
  old_expiry timestamptz,
  new_expiry timestamptz,
  details text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS admin_profiles (
  id uuid PRIMARY KEY,
  full_name text,
  role text NOT NULL DEFAULT 'admin',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_clients_list_id ON clients(list_id);
CREATE INDEX IF NOT EXISTS idx_devices_client_id ON devices(client_id);
CREATE INDEX IF NOT EXISTS idx_devices_last_seen ON devices(last_seen_at);
CREATE INDEX IF NOT EXISTS idx_activations_client_id ON activations(client_id);
CREATE INDEX IF NOT EXISTS idx_sync_logs_list_id ON sync_logs(list_id);

CREATE OR REPLACE FUNCTION gc_set_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END $$;

DROP TRIGGER IF EXISTS provider_lists_updated_at ON provider_lists;
CREATE TRIGGER provider_lists_updated_at BEFORE UPDATE ON provider_lists FOR EACH ROW EXECUTE FUNCTION gc_set_updated_at();

DROP TRIGGER IF EXISTS clients_updated_at ON clients;
CREATE TRIGGER clients_updated_at BEFORE UPDATE ON clients FOR EACH ROW EXECUTE FUNCTION gc_set_updated_at();
