CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS provider_lists (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  source_url text,
  server_url text,
  username text,
  provider_password text,
  expires_at timestamptz,
  provider_status text,
  status text NOT NULL DEFAULT 'unknown',
  max_connections integer NOT NULL DEFAULT 1,
  active_connections integer NOT NULL DEFAULT 0,
  last_sync_at timestamptz,
  last_error text,
  created_by text,
  provider_secret_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS clients (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text,
  phone text,
  plan text NOT NULL DEFAULT 'Mensal',
  list_id uuid REFERENCES provider_lists(id) ON DELETE SET NULL,
  device_limit integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'active',
  activation_code text UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS devices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id uuid REFERENCES clients(id) ON DELETE CASCADE,
  device_uid text,
  device_name text,
  platform text,
  last_seen_at timestamptz,
  status text NOT NULL DEFAULT 'offline',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS activations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id uuid REFERENCES clients(id) ON DELETE CASCADE,
  device_id uuid REFERENCES devices(id) ON DELETE SET NULL,
  activation_code text,
  activated_at timestamptz,
  revoked_at timestamptz
);

CREATE TABLE IF NOT EXISTS sync_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  list_id uuid REFERENCES provider_lists(id) ON DELETE CASCADE,
  status text,
  old_expiry timestamptz,
  new_expiry timestamptz,
  details text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS admin_profiles (
  id uuid PRIMARY KEY,
  full_name text,
  role text NOT NULL DEFAULT 'admin',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_clients_list_id ON clients(list_id);
CREATE INDEX IF NOT EXISTS idx_devices_client_id ON devices(client_id);
CREATE INDEX IF NOT EXISTS idx_devices_last_seen ON devices(last_seen_at);
CREATE INDEX IF NOT EXISTS idx_activations_client_id ON activations(client_id);
CREATE INDEX IF NOT EXISTS idx_sync_logs_list_id ON sync_logs(list_id);

CREATE OR REPLACE FUNCTION gc_set_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END $$;

DROP TRIGGER IF EXISTS provider_lists_updated_at ON provider_lists;
CREATE TRIGGER provider_lists_updated_at BEFORE UPDATE ON provider_lists FOR EACH ROW EXECUTE FUNCTION gc_set_updated_at();

DROP TRIGGER IF EXISTS clients_updated_at ON clients;
CREATE TRIGGER clients_updated_at BEFORE UPDATE ON clients FOR EACH ROW EXECUTE FUNCTION gc_set_updated_at();

CREATE TABLE IF NOT EXISTS admin_auth (
  id uuid PRIMARY KEY,
  email text UNIQUE NOT NULL,
  password_hash text NOT NULL,
  full_name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_admin_auth_email ON admin_auth(lower(email));

CREATE INDEX IF NOT EXISTS idx_devices_client_status ON devices(client_id,status);

ALTER TABLE devices ADD COLUMN IF NOT EXISTS network_online boolean;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS network_rtt_ms numeric;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS network_downlink_mbps numeric;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS network_effective_type text;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS backend_rtt_ms numeric;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS diagnostics_status text DEFAULT 'unknown';
ALTER TABLE devices ADD COLUMN IF NOT EXISTS last_playback_at timestamptz;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS last_playback_error text;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS last_buffer_seconds numeric DEFAULT 0;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS last_stream_name text;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS last_stream_type text;

ALTER TABLE provider_lists ADD COLUMN IF NOT EXISTS health_status text DEFAULT 'unknown';
ALTER TABLE provider_lists ADD COLUMN IF NOT EXISTS health_score integer;
ALTER TABLE provider_lists ADD COLUMN IF NOT EXISTS health_checked_at timestamptz;
ALTER TABLE provider_lists ADD COLUMN IF NOT EXISTS health_details text;

CREATE TABLE IF NOT EXISTS playback_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id uuid REFERENCES clients(id) ON DELETE CASCADE,
  device_id uuid REFERENCES devices(id) ON DELETE CASCADE,
  list_id uuid REFERENCES provider_lists(id) ON DELETE SET NULL,
  event_type text NOT NULL,
  stream_key text,
  stream_name text,
  stream_type text,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  startup_ms integer,
  buffer_seconds numeric,
  network_rtt_ms numeric,
  network_downlink_mbps numeric,
  network_effective_type text,
  online boolean,
  error_code text,
  error_message text,
  details jsonb
);
CREATE INDEX IF NOT EXISTS idx_playback_events_list_time ON playback_events(list_id,occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_playback_events_device_time ON playback_events(device_id,occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_playback_events_stream_time ON playback_events(stream_key,occurred_at DESC);

CREATE TABLE IF NOT EXISTS channel_health (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  list_id uuid REFERENCES provider_lists(id) ON DELETE CASCADE,
  stream_key text NOT NULL,
  stream_name text NOT NULL,
  stream_type text,
  status text NOT NULL DEFAULT 'unknown',
  score integer,
  client_reports integer NOT NULL DEFAULT 0,
  error_reports integer NOT NULL DEFAULT 0,
  buffer_reports integer NOT NULL DEFAULT 0,
  last_error text,
  last_checked_at timestamptz,
  last_ok_at timestamptz,
  details jsonb,
  UNIQUE(list_id,stream_key)
);
CREATE INDEX IF NOT EXISTS idx_channel_health_list_status ON channel_health(list_id,status);
